
spring:   
  datasource:
    url: mysql://mysql:3306/mysql
    username: user
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
